- name: Prepare directories.
  file:
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "{{ cert_src_path }}"
    - "{{ cert_dest_path }}"
    - "{{ registry_data_path }}"
- name: Processing templates
  template:
    src: "templates/{{ item }}.j2"
    dest: "{{ cert_src_path }}/{{ item }}"
  with_items:
    - "{{ cert_config_file }}"
    - "{{ cert_input_file }}"
    - "ca.csr.json"
- name: Generating CA file
  set_fact:
    cert_task: "ca"
- include_role: name="cert"
- name: Get CA content
  shell: "cat {{ cert_src_path }}/{{ ca_output_file }}.pem"
  register: ca_content
- name: Spread CA data to all docker
  include_tasks: spread_ca.yml
  delegate_to: "{{ item }}"
  with_items: "{{ groups['remote'] }}"

- name: Generating cert file
  set_fact:
    cert_profile_name: "server"
    cert_task: "server"
- include_role: name="cert"

- name: Uploading image
  copy:
    src="files/images/registry-2.6.2.tar.gz"
    dest="/tmp"
- name: Loading image
  shell: "docker load -i /tmp/registry-2.6.2.tar.gz"
- name: Uploading starting shell script.
  template:
    src: "templates/docker-registry.sh.j2"
    dest: "/usr/local/bin/docker-registry.sh"
    mode: 0755
- name: Run it
  shell: "/usr/local/bin/docker-registry.sh"
