- name: Trust CA
  blockinfile:
    path: "/etc/pki/tls/certs/ca-bundle.crt"
    block: "{{ ca_content.stdout }}"
  delegate_to: "{{ item }}"
- name: Restart Docker
  service:
    name: docker
    state: restarted
  delegate_to: "{{ item }}"
  ignore_errors: yes
