kubeadm_rpms:
  - "socat-1.7.3.2"
  - "kubectl-{{ main_version }}"
  - "kubernetes-cni-0.6.0"
  - "kubelet-{{ main_version }}"
  - "kubeadm-{{ kubeadm_version }}"
kubeadm_images:
  - "etcd-amd64-{{ etcd_version }}"
  - "kube-apiserver-amd64-{{ main_version }}"
  - "kube-controller-manager-amd64-{{ main_version }}"
  - "kube-proxy-amd64-{{ main_version }}"
  - "kube-scheduler-amd64-{{ main_version }}"
  - "k8s-dns-kube-dns-amd64-{{ dns_version }}"
  - "k8s-dns-sidecar-amd64-{{ dns_version }}"
  - "k8s-dns-dnsmasq-nanny-amd64-{{ dns_version }}"
  - "pause-amd64-{{ pause_version }}"
