- name: copy rpm files
  copy: src=files/{{ item }}  dest=/tmp/{{ item }}
  with_items: "{{ docker_package }}"
- name: copy rpm files
  copy: src=files/docker.engine.rpm   dest=/tmp/
- name: install rpm files
  yum: name=/tmp/{{ item }} state=present
  with_items: "{{ docker_package }}"
- name: install docker rpm
  yum: name=/tmp/docker.engine.rpm state=present
